### ISSUE TITLE
Definição de Escopo do Processo e Produto 

### ISSUE THREAD

**Issue by JonathasSL** [CaiqueR/little-cow#20]
- [x] #18 Estrutura Analítica do Projeto
- [x] #19 Requisitos funcionais e não funcionais
- [x] #31 Descrição do escopo do software
- [ ] Processo
